# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci && npm run build

# Default environment vars
ENV PORT=8080

EXPOSE 8080
CMD ["node", "dist/streamableHttp.js"]
