# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config

# ----- Build Stage -----
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy package and configuration
COPY package.json package-lock.json tsconfig.json ./

# Copy source code
COPY src ./src

# Install dependencies and build
RUN npm ci && npm run build

# ----- Production Stage -----
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts
COPY --from=builder /app/dist ./dist

# Copy package.json for production install
COPY package.json ./

# Install only production dependencies
RUN npm install --production --ignore-scripts

# Default environment vars
ENV PORT=8080

# Expose HTTP port
EXPOSE 8080

# Start the server
# Use STDIO for now to avoid breaking deployment for Smithery
CMD ["node", "dist/stdio.js"]
